
exports.seed = function(knex) {
  return knex('recipes').del()
    .then(function () {
      return knex('recipes').insert([
        {id: 1, name: 'Snickered', serves: 12, ingredients: JSON.stringify(['1/2 cup oats', '1/2 cup cashews', '1/2 cup desiccated coconut', '1 1/4 cup dates, pitted', '6 tbsp crunchy peanut butter', '3 tbsp coconut oil', '2 tbsp maple syrup', '1 tbsp brown rice syrup', '4 tbsp unsweetened almond milk', '2 tbsp cacao powder', '1 tbsp coconut butter']), method: JSON.stringify(['BASE LAYER:', 'Place the oats and cashews in a food processor and process until they have broken down.', ' Add the desicated coconut, 1/4 cup dates, 1Tbsp of peanut buter 1Tbsp coconut oil and 1Tbsp maple syrup and process again until the mixture is fully combined.', 'Transfer the mixture to a lined baking tray and press down with your fingers to form an even base layer.', ' Place the tray in the freezer while you make the caramel layer.', 'CARAMEL LAYER:', 'Place the rest of the dates, 1Tbsp brown rice syrup, the almond milk and 4Tbsp peanut butter in a food processor and process until you reach a smooth consistency.', 'Remove the tray from the freezer and spread evenly over the base layer.', 'Put the tray back in the freezer.', 'CHOCOLATE LAYER:', ' Melt the coconut butter and coconut oil in a pan over a gentle heat.', 'Once melted, take off the heat and stir in the rest of the ingredients until a silky smooth consistency is reached.', 'Leave to cool slightly before spreading evenly over the caramel layer.', ' Place back in the freezer to set for around an hour before cutting into squares and getting into it!', 'Store in the fridge or freezer.'])}, 
        {id: 2, name: 'Bountyful', serves: 12, ingredients: JSON.stringify(['3 cups desiccated coconut', '3 Tbsp honey', '1 tsp vanilla extract', '3 Tbsp coconut oil', '1/4 cup coconut milk', 'High quality dairy-free chocolate']), method: JSON.stringify(['FILLING:', 'Add the coconut to a food processor and blend for about 30 seconds.', 'Add the vanilla, coconut milk and honey and blend again.', 'Fold in the coconut oil and stir well.', 'Transfer to a lined baking in and press down firmly.', 'Place in the freezer for at least 5 hours.', 'CHOCOLATE LAYER:', 'Remove from the freezer and cut into bars.', 'Melt the chocolate then coat the bars in the chocolate.', 'Return to the freezer for a further 15 minutes then get into it!'])}
      ]);
    });
};
